swagger: "2.0"
info:
  description: "创新实践课，宠物交易网站api设计"
  version: "1.0.0"
  title: "Pet-trade"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "pet"
  description: "Everything about your Pets"
- name: "trade"
  description: "trade"
- name: "user"
  description: "Operations about user"
schemes:
- "https"
- "http"
paths:
  /pet:
    post:
      tags:
      - "pet"
      summary: "在个人仓库中新建宠物"
      description: "用于在个人仓库中添加宠物"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: " petName"
        in: "body"
        description: "宠物昵称"
        required: true
        type: "string"
      - name: "petVariety"
        in: "body"
        description: "宠物品种"
        required: true
        type: "string"
      - name: "info"
        in: "body"
        description: "详细介绍"
        required: true
        type: "string"
      - name: "age"
        in: "body"
        description: "年龄"
        required: true
        type: "string"
      - name: "price"
        in: "body"
        description: "价格"
        required: true
        type: "string"
      responses:
        201:
          description: "successful operation"
        400:
          description: "fail"
  
    delete:
      tags:
      - "pet"
      summary: "删除宠物"
      description: ""
      operationId: "deletePet"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "body"
        description: "宠物id"
        required: true
        type: "number"
      - name: "petName"
        in: "body"
        description: "宠物名字"
        required: true
        type: "string"
      responses:
        204:
          description: "success"
        400:
          description: "fail"

  /pet/key:
    get:
      tags:
      - "pet"
      summary: "查找"
      description: "通过宠物品种、昵称、年龄查找宠物"
      operationId: ""
      produces:
      - "application/json"
      parameters:
      - name: "key"
        in: "query"
        description: "关键词"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        404:
          description: "notFound"
  /pet/id:
    PATCH:
      tags:
      - "pet"
      summary: "更新宠物信息"
      description: ""
      operationId: ""
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "body"
        description: "宠物id"
        required: true
        type: "number"
      - name: "petName"
        in: "body"
        description: "宠物昵称"
        required: true
        type: "string"
      - name: "petVariety"
        in: "body"
        description: "宠物品种"
        required: true
        type: "string"
      - name: "age"
        in: "body"
        description: "宠物年龄"
        required: true
        type: "string"
      - name: "price"
        in: "body"
        description: "宠物价格"
        type: "string"
      responses:
        200:
          description: "successful operation"
        400:
          description: "fail"

  /pet/picture:
     post:
      tags:
      - "pet"
      summary: "上传宠物图片x3"
      description: ""
      operationId: "uploadFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "宠物"
        required: true
        type: "integer"
        format: "int64"
      - name: "image"
        in: "formData"
        description: "image to upload"
        required: true
        type: "file"
      responses:
        201:
          description: "successful operation"
        400:
          description: "fail"

  /pet/all:
     get:
      tags:
      - "pet"
      summary: "获取所有宠物"
      description: ""
      operationId: ""
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
        404:
          description: "notFound"

  /user/login:
    post:
      tags:
      - "user"
      summary: "登录"
      description: "使用昵称和密码登录"
      operationId: ""
      produces:
      - "application/json"
      parameters: 
      - name: "userName"
        in: "body"
        description: "用户名"
        required: true
        type: "string"
      - name: "password"
        in: "body"
        description: "密码"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        401:
          description: "fail"
  /user:
    post:
      tags:
      - "user"
      summary: "注册"
      description: ""
      operationId: ""
      produces:
      - "application/json"
      parameters:
      - in: "query"
        name: "userName"
        description: "昵称（不允许重复）"
        type: "string"
        required: true
      - in: "query"
        name: "password"
        description: "密码"
        type: "string"
        required: true
      - in: "query"
        name: "dpassword"
        description: "重复密码"
        type: "string"
        required: true
      responses:
        201:
          description: "successful operation"
        403:
          description: "Invalid Order"
  /user/id:
    patch:
      tags:
      - "user"
      summary: "完善用户信息"
      description: ""
      operationId: "setPersionInfoById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: ""
        required: true
        type: "number"
      - name: "userName"
        in: "path"
        description: ""
        required: true
        type: "string"
      - name: "userName"
        in: "path"
        description: ""
        type: "string"
      - name: "telephone"
        in: "path"
        description: ""
        type: "string"
      - name: "signature"
        in: "path"
        description: ""
        type: "string"
      - name: "address"
        in: "path"
        description: ""
        type: "string"
      
      responses:
        200:
          description: "successful operation"
        400:
          description: "Invalid ID supplied"
  /pet/user/id:    
    get:
      tags:
      - "user"
      summary: "获取主人拥有的宠物"
      description: ""
      operationId: ""
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: ""
        required: true
        type: "number"
      responses:
        200:
          description: "sucess"
        404:
          description: "not found"

  /user/pet:
    post:
      tags:
      - "user"
      summary: "为主人添加宠物"
      description: ""
      operationId: ""
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "query"
        name: "userId"
        required: true
        type: "number"
      - in: "query"
        name: "petId"
        required: true
        type: "number"
      responses:
        200:
          description: "successful operation"
        403:
          description: "fail"

    delete:
      tags:
      - "user"
      summary: "为主人删除宠物"
      description: ""
      operationId: ""
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "query"
        name: "userId"
        required: true
        type: "number"
      - in: "query"
        name: "petId"
        required: true
        type: "number"
      responses:
        200:
          description: "successful operation"
        403:
          description: "fail"
  /user/avatar:
     post:
      tags:
      - "pet"
      summary: "上传用户头像"
      description: ""
      operationId: "uploadFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "用户"
        required: true
        type: "integer"
        format: "int64"
      - name: "image"
        in: "formData"
        description: "image to upload"
        required: true
        type: "file"
      responses:
        201:
          description: "successful operation"
        400:
          description: "fail"

  /trade:
    get:
      tags:
      - "trade"
      summary: "获取交易信息表"
      description: ""
      operationId: ""
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "key"
        in: "query"
        description: "卖家id、买家id、宠物id"
        required: true
        type: "number"
      responses:
        200:
          description: "successful operation"
        403:
          description: "fail"
    post:
      tags:
      - "trade"
      summary: "创建交易信息"
      description: ""
      operationId: ""
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "buyerId"
        in: "query"
        description: "买家id"
        required: true
        type: "number"
      - name: "sellerId"
        in: "query"
        description: "卖家id"
        required: true
        type: "number"
      - name: "petId"
        in: "query"
        description: "宠物id"
        required: true
        type: "number"
      responses:
        201:
          description: "successful operation"
        403:
          description: "fail"
  /trade/deal:
    get:
      tags:
      - "trade"
      summary: "完成交易"
      description: ""
      operationId: ""
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "tradeId"
        in: "query"
        description: "交易id"
        required: true
        type: "number"
      responses:
        201:
          description: "successful operation"
        403:
          description: "fail"